AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20

Resources:
  CopyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: copy_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - S3FullAccessPolicy:
            BucketName: test-experiments-bucket
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
            Enabled: True
